### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by agreco** [ioncreature/webkit-developer-tools-dark-theme#1]
Hey,

I followed the steps to build the Custom style sheet and to error fired back:

ParseError: /blar/blar/Library/Application Support/Google/Chrome/Default/User StyleSheets/Custom.css:242
   238| #-webkit-web-inspector .properties-tree li.parent::before {
   239|   content: url("chrome-devtools://devtools/Images/treeRightTriangleWhite.png") !important;
   240| }
   241| #-webkit-web-inspector .console-group-messages .section.expanded .header::before,

> 242| #-webkit-web-inspector .properties-tree li.parent.expanded::before {
>    243|   content: url("chrome-devtools://devtools/Images/treeDownTriangleWhite.png") !important;
>    244| }
>    245| @-webkit-keyframes webkit-error-level {

"undefined" is invalid, use "from" or "to"

Not sure if I'm building this right but I used the advice on the readme, ping me if it's not enough info.

Cheers
Antonio

**Comment by ioncreature** [comment]
Hi, Antonio. 
Thank you for feedback.

I cannot reproduce your issue on my laptop.
I recently updated doc, so try again, please

My test is:

``` sh
stylus < Custom.styl > Test.css
```

It works fine.
