### ISSUE TITLE
dev tools nav bar layout issues

### ISSUE THREAD

**Issue by mattsawyer77** [ioncreature/webkit-developer-tools-dark-theme#2]
Installed into ~/Library/Application Support/Google/Chrome Canary/Default/User StyleSheets/Custom.css in Chrome Canary 25.0.1363.0. The items in the dev tools nav bar are invisible and seem to be very small.
![Screen Shot 2012-12-17 at 11 15 36 PM](https://f.cloud.github.com/assets/236582/18727/31964cd8-48d2-11e2-877d-17c4111082a1.png)

**Comment by ioncreature** [comment]
Thank you, i'll see it.
